### PR TITLE
Fix typo in contributing guide

### PR DESCRIPTION
**Pull request by webknjaz**
* And also move it to `.github/`, since it's a better place to keep related stuff altogether.

### CODE REVIEW

**Comment by denysdovhan** [comment]
Let's defer it for a while. There's no need to create in root of project for only one file.

**Comment by webknjaz** [comment]
I may add PR/ISSUE templates via subsequent PR

**Comment by denysdovhan** [comment]
There's no need in that for now. We don't have persistent template for all of issues. Nevertheless, if you want you can write a draft here. We'll consider if that would be okay for us.

**Comment by webknjaz** [comment]
ok

**Pull request merged**
